Task-5 Wstępna implementacja UserController
mps4dev/project-jdp-2108-01 pull request #15
Opened 2021-08-26 16:33 UTC by JuliaSidor811

2021-09-02 18:23 UTC, Typhoonic commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +@Transactional
Zostawiłem tą klasę ze względu na niebudowanie się projektu... Musiałbym teraz usunąć wszystkie klasy które są z nią połączone.

2021-09-02 19:39 UTC, Kamil-Krol submitted a review, later dismissed

2021-09-02 21:02 UTC, Anna-Dyrdul approved these changes

2021-09-02 21:54 UTC, DominikBernatowicz commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +@Transactional
wydaje mi się że branch powinien zawierać tylko UserController oraz proste UserDto

2021-09-03 06:43 UTC, Typhoonic commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +@Transactional
Oki, ogarne to ^ ^

2021-09-03 15:27 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +@Transactional
Dokładnie. Musisz usunąć ten plik z swojego brancha i musisz koniecznie zrobić merge aktulanego main bo ten branch jest bardzo stary

2021-09-03 15:29 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +@Transactional
Wtedy te zmiany znikną z FilesChanged bo będą uwzględnione zmiany z main, a projekt będzie się budował

2021-09-03 15:40 UTC, patryk-ziemniak requested changes
User i UserRepository:
- usuń te pliki z swojego brancha, zrób commit
- koniecznie zrób merge aktualnego main
Wtedy zmiany w tych plikach znikną z FilesChanged, bo będą uwzględnione zmiany z main, a projekt będzie się budował

2021-09-03 15:40 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Entity(name = "USERS")
patrz komentarz główny

2021-09-03 15:40 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository<User,Long> {
patrz komentarz główny

2021-09-04 17:28 UTC, DominikBernatowicz approved these changes

2021-09-04 21:55 UTC, patryk-ziemniak approved these changes

2021-09-04 21:56 UTC, merged