task-22 GroupController - rzeczywista implementacja metod
mps4dev/project-jdp-2108-01 pull request #17
Opened 2021-08-27 16:44 UTC by patryk-ziemniak

- implementacja GroupDto na wzór Group
- utworzenie GroupMappera
- nadpisanie jednej metody CrudRepository w GroupRepository
- utworzenie 2 wyjątków użytych w GroupService
- utworzenie GroupService z zależnościami do mappera i kontrolera repozytorium
- rzeczywista implementacja metod w GroupController z zależnością do GroupService

https://projects.kodilla.com/browse/JDP210801-22

2021-08-28 08:31 UTC, mps4dev requested changes

2021-08-28 08:31 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (group.isPresent()) {
tak nie robimy z Optionalem
return repository.findById(id).map(mapper::mapFrom).orElseThrow(() -> new EntityNotFoundException(Group.class, id));

2021-08-28 08:31 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (groupDto.getId() != 0) throw new CreatingObjectWithIdException();
???

2021-08-28 08:31 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (group.isPresent()) {
j.w.

2021-08-28 08:31 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (group.isPresent()) {
j.w.

2021-08-28 11:59 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    private final GroupService service;
Jeżeli jest tylko jeden konstruktor, który wstrzykuje zależność, to Spring sam wie że trzeba wstrzyknąć. Nie potrzeba @Autowired. Chyba, że będzie dodatkowy konstruktor bezparametrowy

2021-08-28 11:59 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/dto/GroupDto.java
> +    private List<Product> products = new ArrayList<>();
Racja, poprawie. Skopiowałem bezmyślnie z Group :D

2021-08-28 12:02 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (group.isPresent()) {
Racja, nie przejrzałem dokumentacji, że jest orElseThrow :)

2021-08-28 12:03 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        if (groupDto.getId() != 0) throw new CreatingObjectWithIdException();
na wszelki wypadek, gdyby ktoś przesłał JSON do metody create z id innym niż zero lub nullem. Wtedy mogłoby zajść update już istniejącego poprzez metodę save() kontrolera repozytorium

2021-08-28 21:18 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        return groupList.stream()
Świetne rozwiązanie! :)

2021-08-28 21:38 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/exception/NoSuchIdException.java
> +public class NoSuchIdException extends Exception {
Tu się zgadzam, zmieniłem nazwę i ustawiłem konstruktor z message

2021-08-28 21:39 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/exception/CreatingObjectWithIdException.java
> +public class CreatingObjectWithIdException extends Exception {
Aplikacja ma być idiotoodporna, dlatego sprawdza czy ktoś nie podał id (inne niż 0 lub null) przy tworzeniu encji, gdy jednak podał to trzeba to zasygnalizować, stąd ten wyjątek. Dodałem do niego message jak w EntityNotFoundException

2021-08-29 06:34 UTC, mps4dev approved these changes

2021-08-29 06:34 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/exception/CreatingObjectWithIdException.java
> +public class CreatingObjectWithIdException extends Exception {
Ale nie podaje sie id jak sie tworzy obiekt.

2021-08-29 08:10 UTC, Anna-Dyrdul approved these changes

2021-08-29 12:27 UTC, merged