task-20 Encja User - testy
mps4dev/project-jdp-2108-01 pull request #36
Opened 2021-09-09 15:59 UTC by patryk-ziemniak

https://projects.kodilla.com/browse/JDP210801-20

2021-09-10 08:31 UTC, mps4dev requested changes

2021-09-10 08:31 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    private void prepareData() {
metody prywatne na koncu klasy

2021-09-10 08:31 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    UserRepository userRepository;
private

2021-09-10 08:31 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/UserRepositoryTestSuite.java
> +    public void userRepositoryGetAll() {
Pomyslalbym nad nazwami metod testujacych, np. shouldReturnAllUsersFromRepository itp...

2021-09-10 21:40 UTC, Kamil-Krol approved these changes

2021-09-11 10:00 UTC, Typhoonic approved these changes

2021-09-11 10:29 UTC, patryk-ziemniak commented
@mps4dev proszę o ponowny review

2021-09-11 10:30 UTC, merged