task-23 CartController - rzeczywista implementacja metod
mps4dev/project-jdp-2108-01 pull request #39
Opened 2021-09-10 21:08 UTC by DominikBernatowicz

2021-09-10 23:12 UTC, patryk-ziemniak requested changes
zrób jeszcze reformat code dla całego pakietu com.kodilla.ecomercee -> PPM -> Reformat Code -> optimize imports też ma być zaznaczone

2021-09-10 23:12 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        repository.findById(cartDto.getId()).orElseThrow(() -> new EntityNotFoundException(Order.class, cartDto.getId()));
zła klasa podana do wyjątku

2021-09-13 11:14 UTC, patryk-ziemniak approved these changes

2021-09-13 11:31 UTC, mps4dev approved these changes

2021-09-13 11:33 UTC, merged