Task 11
mps4dev/project-jdp-2108-01 pull request #4
Opened 2021-08-20 18:34 UTC by Typhoonic

2021-08-20 21:26 UTC, mps4dev requested changes
Pull request nieopisany (brak message komita?)
👎🏻

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    @PostMapping("/{productDto}")
tak to nie przejdzie. W urlu nie mozemy w zaden sposob przeslac obiektu. Potrzebujemy @RequestBody

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void create(@PathVariable ProductDto productDto){}
czemu void?

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    @PutMapping("/{productDto}")
j.w.

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +@RestController
skad ta klasa w tasku 11?

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products = new ArrayList<>();
czy aby na pewno w zamowieniu bedziemy miec liste produktow?

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +public class User {
co to?

2021-08-20 21:26 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
co to za klasa w tym pull requescie?

2021-08-22 19:39 UTC, patryk-ziemniak requested changes

2021-08-22 19:39 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +public class ProductDto {
Klasa zbędna dla tego zadania

2021-08-22 19:39 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Brak relacji do encji Product - zamówienie zawiera listę produktów

2021-08-22 19:49 UTC, Typhoonic commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Miałem listę produktów ;) Marcin pisał, że jest ona nie potrzebna ;)

2021-08-22 19:51 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
widocznie ja się nie znam ¯\_(ツ)_/¯

2021-08-22 19:54 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Już wiem o co mu chodziło - koszyk w którym są produkty ma być przypisany do Order
Choć dla mnie to trochę przekombinowane bo ten koszyk tutaj już jest zbędny w zamówieniu

2021-08-23 05:20 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Zamowienie tworzymy na podstawie koszyka :) Chociaz koszyk jest rzeczywiscie tymczasowym obiektem, to mozemy go pamietac w bazie danych. Na podstawie koszyka tworzymy zamowienie, bo jesli bysmy mieli tylko i wylacznie liste produktow, to jak bysmy pamietali ile sztuk ktorego produktu mamy w zamowieniu? Innym rozwiazaniem byloby wprowadzenie obiektu OrderItem, ktory by mowil jaki produkt w jakiej ilosci jest w zamowieniu.

2021-08-23 05:22 UTC, mps4dev requested changes
👎🏻

2021-08-23 05:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +package com.kodilla.ecommercee.domain;
powinno byc w pakiecie com.kodilla.ecommercee.dto jak juz, ale po co to do implementacji encji?

2021-08-23 05:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private Long id;
po co to?

2021-08-23 13:20 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Koszyk w takim razie też nie rozwiązuje kwestii ilości zamówionego produktu.
Stąd też najlepiej byłoby zrobić encję OrderItem mający pola Product oraz quantity. Wtedy w Order oraz Cart byłyby listy OrderItem. W momencie składania zamówienia przez endpoint CartController lista byłaby przepisywana z Cart do Order (razem z id użytkownika), a Cart byłby usuwany z bazy danych.
Cart byłby zapisywany do bazy danych tylko tymczasowo do momentu kiedy nie zostanie "wyczyszczony" przez użytkownika lub gdy złożone zostanie zamówienie. Tym samym użytkownik może kontynuować kompletowanie zamówienia w późniejszym czasie.

2021-08-23 18:17 UTC, mps4dev approved these changes

2021-08-23 18:20 UTC, Anna-Dyrdul approved these changes

2021-08-23 18:41 UTC, patryk-ziemniak approved these changes

2021-08-23 19:33 UTC, patryk-ziemniak approved these changes

2021-08-24 05:18 UTC, mps4dev approved these changes

2021-08-24 05:18 UTC, merged