Added documentation for OrderController endpoints
mps4dev/project-jdp-2108-01 pull request #40
Opened 2021-09-11 11:04 UTC by Typhoonic

2021-09-11 13:15 UTC, patryk-ziemniak requested changes

2021-09-11 13:15 UTC, patryk-ziemniak commented on docs/OrderEndpoints.md
> +## 2. Get orders with exact ID
get order*

2021-09-11 13:15 UTC, patryk-ziemniak commented on docs/OrderEndpoints.md
> +`GET /v1/order`
daj jeszcze `/` po `order` żeby ujednolicić w całym pliku

2021-09-11 13:15 UTC, patryk-ziemniak commented on docs/OrderEndpoints.md
> +Insert cartId instead of `<cartId>`
złącz to w jedną linię

> Insert userId instead of `<userId>` and cartId instead of `<cartId>`.

2021-09-11 21:17 UTC, patryk-ziemniak approved these changes

2021-09-12 20:27 UTC, Kamil-Krol approved these changes

2021-09-12 23:16 UTC, merged