Task - 16 Encja Order - testy
mps4dev/project-jdp-2108-01 pull request #42
Opened 2021-09-13 16:19 UTC by Anna-Dyrdul

2021-09-13 19:19 UTC, mps4dev requested changes

2021-09-13 19:19 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/OrderRepositoryTestSuite.java
> +        userRepository.save(user);
co testujemy? zachowywanie encji user, cart i order? To ma byc test jednostkowy, wiec w sekcji When jest tylko save(order)

2021-09-13 19:19 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/OrderRepositoryTestSuite.java
> +        try {
czemu try w tescie?

2021-09-13 19:19 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/OrderRepositoryTestSuite.java
> +        try {
jw.

2021-09-13 19:19 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/OrderRepositoryTestSuite.java
> +        userRepository.save(user);
dla mnie w then powinno byc tylko orderRepository.save(order);

2021-09-14 07:39 UTC, DominikBernatowicz approved these changes

2021-09-14 10:07 UTC, mps4dev approved these changes

2021-09-14 10:07 UTC, merged