task-12 Encja Product - implementacja
mps4dev/project-jdp-2108-01 pull request #5
Opened 2021-08-20 18:59 UTC by Kamil-Krol

- stworzyłem encję Product

- skopiowałem encję Group z task-13

- stworzyłem Dao ProductRepository

- dodałem Lomboka i adnotację @NotNull

2021-08-20 20:37 UTC, patryk-ziemniak requested changes
- brak ceny produktu
- brak opisu (?) produktu
- ilość w tym przypadku nie potrzebna (?) - to jest baza danych produktów - inaczej lista dostępnych produktów w sklepie - kwestie ilości zamawianego produktu w koszyku można by rozwiązać opakowując Product klasą Item - mającym Product i quantity
- dostępność powinna być raczej reprezentowana przez ilość sztuk produktu na magazynie

(?) - oznaczyłem rzeczy do uzgodnienia

2021-08-20 21:22 UTC, mps4dev requested changes
👎🏻

2021-08-20 21:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "ID")
zbędne, z defaultu nazwa będzie taka jak pola, czyli id

2021-08-20 21:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "NAME")
j.w.

2021-08-20 21:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@NoArgsConstructor
czemu w ogole encja Group jest w pull requescie dotyczacym encji Product?

2021-08-20 21:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private long id;
wszędzie - usunąć @Column jeśli zbędne

2021-08-20 21:22 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
https://github.com/mps4dev/project-jdp-2108-01/blob/main/specs/product.spec.json - proszę zauważyc, ze w projekcie mamy specyfikacje ;) tam sa podane pola, jakie powinny byc

2021-08-20 21:24 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@NoArgsConstructor
Nie da się utworzyć relacji pomiędzy encjami, nie posiadając drugiej encji. Wtedy projekt się nie zbuduje

2021-08-22 15:32 UTC, patryk-ziemniak requested changes

2021-08-22 15:32 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private long id;
Jeżeli jest @GeneratedValue to nie jest potrzebne @NotNull

2021-08-22 15:32 UTC, patryk-ziemniak commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private int value;
W specyfikacji jest `price`, nie `value`

2021-08-22 15:39 UTC, patryk-ziemniak approved these changes

2021-08-23 05:24 UTC, mps4dev requested changes
W encji Group zostawic tylko to, co konieczne w

2021-08-23 05:24 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@NoArgsConstructor
klasa pusta a nie cala encja - robisz za kogos zadanie

2021-08-23 07:35 UTC, Anna-Dyrdul approved these changes

2021-08-23 13:53 UTC, patryk-ziemniak approved these changes

2021-08-23 18:21 UTC, mps4dev approved these changes

2021-08-23 18:28 UTC, Anna-Dyrdul submitted a review, later dismissed

2021-08-23 19:28 UTC, patryk-ziemniak approved these changes

2021-08-24 10:06 UTC, Anna-Dyrdul approved these changes

2021-08-24 21:39 UTC, mps4dev approved these changes

2021-08-24 21:40 UTC, merged