task-4 OrderController - wstepna implementacja endpointow
mps4dev/project-jdp-2108-01 pull request #6
Opened 2021-08-20 20:11 UTC by Anna-Dyrdul

2021-08-20 20:47 UTC, patryk-ziemniak submitted a review, later dismissed

2021-08-20 21:18 UTC, mps4dev requested changes
👎🏻

2021-08-20 21:18 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +package com.kodilla.ecommercee.domain;
to raczej w pakiecie dto a nie domain

2021-08-20 21:18 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +public class Order {
po co ci ta klasa?

2021-08-22 19:30 UTC, patryk-ziemniak submitted a review, later dismissed

2021-08-23 05:17 UTC, mps4dev requested changes
👎🏻

2021-08-23 05:17 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +import com.kodilla.ecommercee.dto.*;
przenies klase do pakietu com.kodilla.ecommercee.controller
Nie robmy importow z gwiazdka

2021-08-23 13:35 UTC, patryk-ziemniak approved these changes

2021-08-23 18:14 UTC, mps4dev approved these changes
👍🏻

2021-08-23 18:19 UTC, merged

2021-08-23 18:19 UTC, mps4dev approved these changes